import '@/styles/globals.css';
import '@/styles/index.css';
import type { Metadata } from 'next';
import { layoutStyle } from './layout.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<body className={layoutStyle}>{children}</body>
		</html>
	);
}
