#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"                                                                                                                                                                                                                               

docker compose -f "$SCRIPT_DIR/../apps/backend/docker/db-compose.yml" up 